// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxuKlUMXA_ArrOTlrzj_WbMA_AAWxPV7s',
    appId: '1:1097180414537:web:20d9439cf9f772252eb598',
    messagingSenderId: '1097180414537',
    projectId: 'travel-guide-671cd',
    authDomain: 'travel-guide-671cd.firebaseapp.com',
    storageBucket: 'travel-guide-671cd.firebasestorage.app',
    measurementId: 'G-GG38JCCHP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbuwFNC7r84o41RP_dSxHukDQyrxA1kFA',
    appId: '1:1097180414537:android:9036445e4ab69ece2eb598',
    messagingSenderId: '1097180414537',
    projectId: 'travel-guide-671cd',
    storageBucket: 'travel-guide-671cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPU0kK0GYfmSRKx2nnC3f27J3rW42fc_w',
    appId: '1:1097180414537:ios:bcc576d948eb29ae2eb598',
    messagingSenderId: '1097180414537',
    projectId: 'travel-guide-671cd',
    storageBucket: 'travel-guide-671cd.firebasestorage.app',
    iosBundleId: 'com.example.travelGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPU0kK0GYfmSRKx2nnC3f27J3rW42fc_w',
    appId: '1:1097180414537:ios:bcc576d948eb29ae2eb598',
    messagingSenderId: '1097180414537',
    projectId: 'travel-guide-671cd',
    storageBucket: 'travel-guide-671cd.firebasestorage.app',
    iosBundleId: 'com.example.travelGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxuKlUMXA_ArrOTlrzj_WbMA_AAWxPV7s',
    appId: '1:1097180414537:web:4ddc2ce91ad645992eb598',
    messagingSenderId: '1097180414537',
    projectId: 'travel-guide-671cd',
    authDomain: 'travel-guide-671cd.firebaseapp.com',
    storageBucket: 'travel-guide-671cd.firebasestorage.app',
    measurementId: 'G-KJKNZW2SHE',
  );
}
